accounts/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'login$', 'accounts.views.persona_login', name='persona_login'),
    url(
        r'logout$',
        'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name='logout'
    ),
]

lists/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^new$', 'lists.views.new_list', name='new_list'),
    url(r'^user/(.+)/$', 'lists.views.my_lists', name='my_lists'),
    url(r'^(\d+)/share$', 'lists.views.share_list', name='share_list'),
]

superlists/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.utils import timezone

class User(models.Model):
	email = models.EmailField(primary_key=True)
	last_login = models.DateTimeField(default=timezone.now)
	REQUIRED_FIELDS = []
	USERNAME_FIELD = 'email'

	def is_authenticated(self):
		return True

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='shared_with'
    )

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @property
    def name(self):
        return self.item_set.first().text

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from lists.models import Item, List
from django.core.exceptions import ValidationError

EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You can't have duplicate items"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            })
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated():
            return List.create_new(first_item_text=self.cleaned_data['text'],
                                   owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse

def persona_login(request):
	user = authenticate(assertion=request.POST['assertion'])
	if user:
		login(request, user)
	return HttpResponse("OK")

lists/views.py
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import get_user_model


from lists.models import Item, List
from lists.forms import ItemForm, ExistingListItemForm, NewListForm

User = get_user_model()


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)

    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(
            for_list=list_, data=request.POST
        )
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form})


def new_list(request):
    form = NewListForm(data=request.POST)

    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    else:
        return render(request, 'home.html', {'form': form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    shared_lists = List.objects.filter(shared_with=owner)
    return render(
        request,
        'my_lists.html',
        {'owner': owner, 'shared_lists': shared_lists}
    )


def share_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    if request.method == 'POST':
        try:
            user = User.objects.get(email=request.POST['email'])
            list_.shared_with.add(user)
        except ObjectDoesNotExist:
            list_.shared_with.create(email=request.POST['email'])
    return redirect(list_)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
	    <title>To-Do lists</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
		<link href="/static/base.css" rel="stylesheet" media="screen">
	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
			<a class="navbar-brand" href="/">Superists</a>

			{% if user.email %}
		        <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'logout' %}">Log out</a>
		        <span class="navbar-text navbar-right">Logged in as {{ user.email }}</span>
		        <a class="btn navbar-btn navbar-right" id="id_mylists" href="{% url 'my_lists' user.email %}">My Lists</a>
		    {% else %}
		        <a class="btn navbar-btn navbar-right" id="id_login" href="#">Sign in</a>
		    {% endif %}

		</nav>
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						{% block list_form %}
						<form method="POST" action="{% block form_action %}{% endblock %}">
							{{ form.text }}
							{% csrf_token %}
							{% if form.errors %}
								<div class="form-group has-error">
									<span class="help-block">{{ form.text.errors }}</span>
								</div>
							{% endif %}
						</form>
						{% endblock %}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block table %}
					{% endblock %}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block extra_content %}
					{% endblock %}
				</div>
			</div>
		</div>
		<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
		<script src="https://login.persona.org/include.js"></script>
		<script type="text/javascript" src="/static/list.js"></script>
		<script type="text/javascript" src="/static/accounts.js"></script>
		<script type="text/javascript">
		$(document).ready(function(){
			var user = "{{user.email}}" || null;
			var token = "{{ csrf_token }}";
			var urls = {
				login: "{% url 'persona_login' %}",
				logout: null
			};

			Superlists.Accounts.initialize(navigator, user, token, urls);
		})
		</script>
	</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do List{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do List{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
{% block table %}
        <h4 id="id_list_owner">{{ list.owner.email }}</h4>
		<table id="id_list_table" class="table">
			{% for item in list.item_set.all %}
				<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
			{% endfor %}
		</table>
        <div>Shared With:</div>
        <ul>
            {% for sharee in list.shared_with.all %}
            <li class="list-sharee">{{ sharee.email }}</li>
            {% endfor %}
        </ul>
        <div>Share: </div>
        <form action="{% url 'share_list' list.id %}" method="POST">
            {% csrf_token %}
           <input type="text" name="email" placeholder="your-friend@example.com" >
        </form>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block list_form %}{% endblock %}
{% block header_text %}My Lists{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s Lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
        <li><a href="{{list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
    <ul>
        {% for list in shared_lists %}
        <li><a href="{{list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}